### ISSUE TITLE
Does pmem-redis support failure recovery?

### ISSUE THREAD

**Issue by sihangliu** [pmem/pmem-redis#10]
I wonder what compile flags do I need to set in order to make sure data on DCPMM can be recovered after a power failure? 
Could you explain more about the AEP_COW flag? How does it affect data persistence and recovery?

**Comment by KVKIT** [comment]
As normal Redis, it supports to recover from power failure only if the AOF always is set.

AEP_COW is used to support copy-on-write on the memory mapped space from AEP in user space, because kernel doesn't support it.
